-- 1. Tabulka profilů (veřejná data)
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  username text unique,
  full_name text,
  avatar_url text,
  bio text,
  age int,
  birth_date date, -- PRO DYNAMICKÝ VĚK
  gender text CHECK (gender IN ('male', 'female')), -- POHLAVÍ
  target_gender text DEFAULT 'both' CHECK (target_gender IN ('men', 'women', 'both')), -- PREFERENCE
  radar_radius int DEFAULT 10, -- RADIUS
  notify_proximity boolean DEFAULT true, -- NOTIFIKACE
  notify_likes boolean DEFAULT true, -- NOTIFIKACE
  deletion_scheduled_at timestamp with time zone, -- SOFT DELETE
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Tabulka statistik (body count, coins, etc.)
create table if not exists public.user_stats (
  user_id uuid references public.profiles(id) not null primary key,
  body_count int default 0,
  weekly_score int default 0, -- TÝDENNÍ SKÓRE
  coins int default 50,
  ai_credits int default 3,
  invite_code text unique,
  invites_left int default 5,
  is_premium boolean default false,
  premium_until timestamp with time zone
);

-- 3. Tabulka transakcí
create table if not exists public.transactions (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) not null,
  amount numeric,
  currency text default 'CZK',
  package_id text,
  status text default 'COMPLETED',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Tabulka Beta Kódů
create table if not exists public.beta_codes (
  id bigint generated by default as identity primary key,
  code text unique not null,
  is_claimed boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Tabulka Deníku (Journal)
CREATE TABLE IF NOT EXISTS public.journal_entries (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id uuid REFERENCES public.profiles(id) NOT NULL,
    name text NOT NULL,
    date date NOT NULL,
    rating int CHECK (rating >= 1 AND rating <= 5),
    partner_age int,
    tags text[],
    notes text,
    avatar_url text,
    linked_profile_id uuid REFERENCES public.profiles(id), -- PROPOJENÍ S USEREM
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Tabulka Lajků (Likes)
CREATE TABLE IF NOT EXISTS public.likes (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    from_user_id uuid REFERENCES public.profiles(id) NOT NULL,
    to_user_id uuid REFERENCES public.profiles(id) NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(from_user_id, to_user_id)
);

-- 7. Tabulka Notifikací
CREATE TABLE IF NOT EXISTS public.notifications (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id uuid REFERENCES public.profiles(id) NOT NULL,
    type text NOT NULL CHECK (type IN ('like', 'proximity', 'system')),
    content text NOT NULL,
    is_read boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Tabulka Galerie (Fotky)
CREATE TABLE IF NOT EXISTS public.gallery_images (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id uuid REFERENCES public.profiles(id) NOT NULL,
    image_url text NOT NULL,
    is_private boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS Policies (Bezpečnost)
alter table public.profiles enable row level security;
alter table public.user_stats enable row level security;
alter table public.transactions enable row level security;
alter table public.beta_codes enable row level security;
alter table public.journal_entries enable row level security;
alter table public.likes enable row level security;
alter table public.notifications enable row level security;
alter table public.gallery_images enable row level security;

-- Profiles
create policy "Public profiles are viewable by everyone." on profiles for select using ( deletion_scheduled_at IS NULL );
create policy "Users can insert their own profile." on profiles for insert with check ( auth.uid() = id );
create policy "Users can update own profile." on profiles for update using ( auth.uid() = id );

-- Stats
create policy "Public stats are viewable by everyone." on user_stats for select using ( true );
create policy "Users can update own stats." on user_stats for update using ( auth.uid() = user_id );

-- Journal
create policy "Users can CRUD their own journal entries" on public.journal_entries for all using (auth.uid() = user_id);

-- Likes
create policy "Users can insert likes" on public.likes for insert with check (auth.uid() = from_user_id);
create policy "Users can see own likes" on public.likes for select using (auth.uid() = from_user_id OR auth.uid() = to_user_id);

-- Notifications
create policy "Users can see own notifications" on public.notifications for select using (auth.uid() = user_id);
create policy "Anyone can insert notification" on public.notifications for insert with check (auth.role() = 'authenticated');

-- Gallery
create policy "Public images are viewable by everyone" on public.gallery_images for select using (is_private = false OR auth.uid() = user_id);
create policy "Users can manage their own gallery" on public.gallery_images for all using (auth.uid() = user_id);

-- Transactions & Codes
create policy "Users see own transactions." on transactions for select using ( auth.uid() = user_id );
create policy "Anyone can read codes." on beta_codes for select using ( true );

-- Trigger pro nové uživatele
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, username)
  values (new.id, new.email, new.raw_user_meta_data->>'username');
  
  insert into public.user_stats (user_id, invite_code, invites_left)
  values (
    new.id, 
    'LOV-' || substring(md5(random()::text) from 0 for 6),
    5
  );
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();